7101 create pbf login page
bcgov/moh-hnweb pull request #107
Opened 2022-08-08 17:24 UTC by AnumehaSrivastava05

UI implementation

2022-08-08 17:30 UTC, AnumehaSrivastava05 commented
Please ignore ViewPatientRegistration.vue and ViewPatientRegistrationHome.vue . It's only added for testing and will be done as a part of https://dev.azure.com/cgi-vic-hlth/HNWeb/_workitems/edit/6994

2022-08-09 22:46 UTC, weskubo-cgi requested changes

2022-08-11 22:31 UTC, weskubo-cgi requested changes

2022-08-11 22:31 UTC, weskubo-cgi commented on frontend/src/components/template/TheHeader.vue
> +    */
Please check indentation on comment.

2022-08-11 22:31 UTC, weskubo-cgi commented on frontend/src/components/template/TheHeader.vue
> +        title = config.APP_TITLE || import.meta.env.VITE_APP_TITLE
Instead of defining a variable I would just return directly from the if and else.

2022-08-11 22:31 UTC, weskubo-cgi commented on frontend/src/views/PBFLogin.vue
> +        <p>This application supports Population Based Funding clinics with patient and provider registrations. Clinics can also validate and update patient addresses via HCIMWeb, which is available i
Should we raise this as a Sprint task for Leah to follow up on? There's no "menu bar" to use in our app.

2022-08-11 22:31 UTC, weskubo-cgi commented on frontend/src/router/index.js
> +    // PBFUser should be sent to Patient Registration page
I don't think this was refactored correctly. The permissions logic is now only executed for PBFLogin. You should be able to use a single if (with or) statement and then conditionally navigate based on if to.name === 'Login' or else.

2022-08-12 18:43 UTC, weskubo-cgi approved these changes

2022-08-15 16:05 UTC, merged