9067 pbf disable search for inactive payees
bcgov/moh-hnweb pull request #181
Opened 2023-02-28 19:21 UTC by daveb-hni

2023-02-28 20:33 UTC, weskubo-cgi requested changes

2023-02-28 20:55 UTC, daveb-hni commented on frontend/src/views/patientregistration/ViewPatientRegistration.vue
> +        this.alertStore.setErrorAlert(`Your payee number is not active.  Please contact <PBF support contact> to inquire about activating your payee number`)
Added TODO

2023-02-28 20:55 UTC, daveb-hni commented on frontend/src/views/patientregistration/ViewPatientRegistration.vue
> +      console.log(`User ${bcscPayeeMapping.bcscGuid} Payee ${bcscPayeeMapping.payeeNumber} is Active: ${bcscPayeeMapping.payeeIsActive}`)
removed

2023-02-28 20:55 UTC, daveb-hni commented on frontend/src/views/patientregistration/ViewPatientRegistration.vue
> +        console.log('Deactivating Submit')
removed

2023-02-28 20:57 UTC, daveb-hni commented on backend/src/main/java/ca/bc/gov/hlth/hnweb/service/PBFClinicPayeeService.java
> +        List<PBFClinicPayee> pbfClinicPayees = pbfClinicPayeeRepository.findActiveByPayeeNumber(payeeNumber);
Was returning the list in case we needed more info. But as it's not being used now a count would be cleaner.

2023-02-28 20:57 UTC, daveb-hni commented on frontend/src/views/patientregistration/ViewPatientRegistration.vue
>        showModal: false,
removed, it is unused

2023-02-28 21:13 UTC, daveb-hni commented on backend/src/test/java/ca/bc/gov/hlth/hnweb/controller/BcscPayeeMappingControllerTest.java
> +        assertEquals(true, bcscPayeeMappingResponse.getPayeeIsActive());
Yup, changed to assertTrue, also for other tests. It was returning an enum previously hence the object compare.

2023-02-28 22:07 UTC, weskubo-cgi approved these changes

2023-03-01 19:56 UTC, weskubo-cgi approved these changes
Final change looks good.

2023-03-07 20:40 UTC, merged