5081 r34 update group member
bcgov/moh-hnweb pull request #31
Opened 2022-01-12 18:46 UTC by AnumehaSrivastava05

2022-01-12 20:32 UTC, weskubo-cgi requested changes
I believe Dave B will have a look as well.

2022-01-12 20:32 UTC, weskubo-cgi commented on frontend/src/views/groupmember/UpdateGroupMember.vue
> +}
I'm not sure this validation works quite as expected. If you don't enter either field then they both show up as required which isn't technically correct. I think this validation might be best handled manually. E.g. "At least one of Group Member or Department Number is required" See PhnInquiry.vue.

2022-01-12 20:32 UTC, weskubo-cgi commented on frontend/src/services/GroupMemberService.js
> +
Extra whitespace not required.

2022-01-13 17:26 UTC, weskubo-cgi commented on frontend/src/views/groupmember/UpdateGroupMember.vue
> +      validateGroupNumber: helpers.withMessage(
Formatting is inconsistent: required should be on next line and validateGroupNumber should be indented.

2022-01-13 19:24 UTC, daveb-hni reviewed
Minor API suggestions, otherwise everything covered for UI

2022-01-13 19:33 UTC, weskubo-cgi commented on frontend/src/util/validators.js
> +export const VALIDATE_OPTIONAL = "Field is required"
I will remove this.

2022-01-13 19:34 UTC, weskubo-cgi commented on frontend/src/router/index.js
> +import Employees from './../views/Employees.vue'
I have removed the file.

2022-01-13 19:35 UTC, weskubo-cgi commented on frontend/src/components/template/TheNavBar.vue
>          <li id="manage-employees-link" :class="tabClass($route, 'ManageEmployees')">
The argument passed in should be a path, not the component name. I have fixed this.

2022-01-13 20:59 UTC, weskubo-cgi commented on backend/src/main/java/ca/bc/gov/hlth/hnweb/controller/GroupMemberController.java
> +				RPBSPEE0 pee0Request = rpbspee0Converter.convertRequest(updateNumberAndDeptRequest);
Fixed.

2022-01-13 20:59 UTC, weskubo-cgi commented on backend/src/main/java/ca/bc/gov/hlth/hnweb/controller/GroupMemberController.java
> +		// Include all Error and Warning messages but
Fixed.

2022-01-13 21:47 UTC, merged