5078 r30 add group
bcgov/moh-hnweb pull request #39
Opened 2022-01-26 18:14 UTC by AnumehaSrivastava05

2022-01-27 18:35 UTC, weskubo-cgi requested changes

2022-01-27 18:35 UTC, weskubo-cgi commented on frontend/src/main.js
> +  library.add(faPlus)
I don't think we are using faPlus. To improve performance and minimize size we don't want to include anything that's unused.

2022-01-27 18:35 UTC, weskubo-cgi commented on frontend/src/main.js
> +import { faCheckCircle, faChevronDown, faExclamationCircle, faExclamationTriangle, faInfoCircle, faPlus, faQuestionCircle, faSpinner, faTimes, faTrashAlt } from '@fortawesome/free-solid-svg-icons'
I don't think we are using faPlus. To improve performance and minimize size we don't want to include anything that's unused.

2022-01-27 18:35 UTC, weskubo-cgi commented on frontend/src/util/validators.js
> +export function validatePHNFormat(phn) {
I don't think this needs to be exported. It was meant as a "private" function and we aren't using in AddGroupMember anymore.

2022-01-27 18:35 UTC, weskubo-cgi commented on frontend/src/views/groupmember/AddGroupMember.vue
> +          <AppDateInput :e-model="v$.coverageEffectiveDate" id="dp-input-coverageEffectiveDate" label="Coverage Effective Date" tooltip tooltipText="Date always defaults to first day of the month"
The id shouldn't have "dp-input-" as a prefix. This is something that the datepicker component will assign.

2022-01-27 18:35 UTC, weskubo-cgi commented on frontend/src/views/groupmember/AddGroupMember.vue
> +      this.dependents.push(dependentPHN);
Trailing semicolon not required.

2022-01-27 18:35 UTC, weskubo-cgi commented on frontend/src/views/groupmember/AddGroupMember.vue
> +        <AppCol class="col4">
Can we make this col3 for consistency with other fields?

2022-01-27 18:35 UTC, weskubo-cgi commented on frontend/src/views/groupmember/AddGroupMember.vue
> +          <AppInput :e-model="v$.homeAddress.postalCode" id="postalCode" label="Postal Code" type="text" v-model.trim="homeAddress.postalCode" />
Can we make this col3 for consistency with other fields?

2022-01-27 18:35 UTC, weskubo-cgi commented on frontend/src/views/groupmember/AddGroupMember.vue
> +        <AppCol class="col4">
Can we make this col3 for consistency with other fields?

2022-01-27 18:35 UTC, weskubo-cgi commented on frontend/src/views/groupmember/AddGroupMember.vue
> +        <AppCol class="col7">
I think all the address fields can be col6.

2022-01-27 18:35 UTC, weskubo-cgi commented on frontend/src/views/groupmember/AddGroupMember.vue
> +  <br />
Indentation is off.

2022-01-27 18:35 UTC, weskubo-cgi commented on frontend/src/views/groupmember/AddGroupMember.vue
> +        console.log(isValid)
Please remove console.log once development is complete.

2022-01-27 18:35 UTC, weskubo-cgi commented on frontend/src/views/groupmember/AddGroupMember.vue
> +      this.addMode = true
this.result should be reset as well.

2022-01-27 18:35 UTC, weskubo-cgi commented on frontend/tests/e2e/pages/groupmember/AddGroupMember.js
> +import { Selector } from 'testcafe';
Trailing commas aren't required in this file.

2022-01-27 19:04 UTC, daveb-hni commented on frontend/src/views/groupmember/AddGroupMember.vue
> +        <AppButton @click="resetForm()" mode="secondary" type="button">Clear</AppButton>
Clear button doesn't clear content in the Dependent PHN field but not sure if this is significant as this data is not submitted directly.

2022-01-28 20:27 UTC, weskubo-cgi approved these changes
Changes look good.

2022-01-28 20:32 UTC, merged