6320 response codes not encluded with response message
bcgov/moh-hnweb pull request #73
Opened 2022-04-13 22:50 UTC by AnumehaSrivastava05

2022-04-19 17:25 UTC, weskubo-cgi requested changes

2022-04-19 19:05 UTC, weskubo-cgi requested changes

2022-04-19 19:20 UTC, weskubo-cgi approved these changes

2022-04-21 22:22 UTC, daveb-hni reviewed
Please see comment

2022-04-21 22:22 UTC, daveb-hni commented on frontend/src/views/groupmember/CancelDependent.vue
> +          this.$store.commit('alert/setSuccessAlert', this.result.message || 'Transaction successful')
This still has hardcoded default but previous one doesn't.

2022-04-22 18:42 UTC, daveb-hni approved these changes
Last commit of removing hardcoded messages looks good.

2022-04-25 16:10 UTC, merged